v?: Dev to Trunk
gocodebox/lifterlms pull request #1232
Opened 2020-07-13 16:57 UTC by thomasplevy

Fixes #869 via #874

2020-07-20 20:19 UTC, thomasplevy commented
I can't find a *good* way to reduce method length for the 2 issues reported by CodeClimate.

2020-07-20 22:00 UTC, thomasplevy commented
Pending release asset

[lifterlms-4.2.0.zip](https://github.com/gocodebox/lifterlms/files/4950214/lifterlms-4.2.0.zip)

2020-07-20 22:03 UTC, thomasplevy commented
@eri-trabiccolo All CI tests are passing, preflight manual tests look good, thumbs up from you and I'll ship it tomorrow

2020-07-21 13:13 UTC, eri-trabiccolo requested changes
I just noticed some minor doc cs issues, I don't know if you want to fix them now.
For the rest **thumbs up**, ship it.

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php
>   *                Also, add order note about the enrollment deletion only if it actually occurred.
```suggestion
 *              @see `LLMS_Controller_Orders->on_deleted_enrollment()` in `includes\controllers\class.llms.controller.orders.php`.
 *              Also, add order note about the enrollment deletion only if it actually occurred.
```

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/admin/post-types/meta-boxes/class.llms.meta.box.order.enrollment.php
>  	 *                Also, add order note about the enrollment deletion only if it actually occurred.
```suggestion
	 *              @see `LLMS_Controller_Orders->on_deleted_enrollment()` in `includes\controllers\class.llms.controller.orders.php`.
	 *              Also, add order note about the enrollment deletion only if it actually occurred.
```

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/class.llms.view.manager.php
>   *               query args in the request URI.
```suggestion
 *              Added `modify_display_free_enroll_form` method.
 *              `get_url` method modified so to take into account already present
 *              query args in the request URI.
```

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/controllers/class.llms.controller.orders.php
>   *               Also `llms_unenroll_on_error_order` fiter hook added.
```suggestion
 *              Also `llms_unenroll_on_error_order` fiter hook added.
```

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/controllers/class.llms.controller.orders.php
>  	 * @param  LLMS_Order $order Instance of an LLMS_Order
```suggestion
	 * @param LLMS_Order $order Instance of an LLMS_Order.
```

2020-07-21 13:13 UTC, eri-trabiccolo commented on includes/models/model.llms.student.php
>  	 *                Added filter to allow customization of object parent data.
```suggestion
	 *              Added filter to allow customization of object parent data.
```

2020-07-21 16:53 UTC, eri-trabiccolo commented on includes/class.llms.view.manager.php
>   *               query args in the request URI.
not sure why this and the other two above are labeled as "outdated"...

2020-07-21 23:16 UTC, merged