Engagements cleanup and enhancements
gocodebox/lifterlms pull request #1272
Opened 2020-08-04 20:34 UTC by thomasplevy

## Description

Refactors admin panel code to share image upload field HTML and JS between metaboxes and settings fields

## How has this been tested?

Manually, existing unit tests

This needs more testing, I plan to write some e2e tests (maybe)

## Screenshots 

## Types of changes

Updates

## Checklist:
- [ ] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-08-04 20:34 UTC, thomasplevy commented
@eri-trabiccolo I included the code from #1270 in this PR in order to include additional settings/css changes that may be required.

2020-08-05 12:06 UTC, eri-trabiccolo requested changes

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin-settings.js
> +		 * @param {Object} event JS event object.
```suggestion
		 * @param {Object} e     JS event object.
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin-settings.js
> +		 * @param {Integer} id   WP Attachment ID of the image
```suggestion
		 * @param {Object}  $btn The jQuery object of the clicked button.
		 * @param {Integer} id   WP Attachment ID of the image.
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin-settings.js
> +			return window.llms.admin_fields.image.update_image( $btn, e );
we don't have any `e` here

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +				e.preventDefault();
```suggestion
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +				e.preventDefault();
```suggestion
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +			$( '.llms-image-field-remove' ).on( 'click', function( e ) {
```suggestion
			$( '.llms-image-field-remove' ).on( 'click', function() {
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +		this.bind = function() {
We don't need to prevent the default behavior of the click event on button, so we can remove those lines, right?
Also, it doesn't seem that `open_media_lib()` uses the `event` parameter at all.

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +		this.open_media_lib = function( $btn, event ) {
```suggestion
		 * @return {Void}
		 */
		this.open_media_lib = function( $btn ) {
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +			}
This, as in other places, looks like an indentation issue when declaring vars.
It's not in our code editors, but I'm not sure if this is the _right_ way to indent, nor if there's one.

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +				$preview = $btn.prevAll( 'img.llms-image-field-preview' )
```suggestion
				$preview = $btn.prevAll( 'img.llms-image-field-preview' ),
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +		 * @param {Integer} id   WP Attachment ID of the image
```suggestion
		 * @param {Object}  $btn The jQuery object of the clicked button.
		 * @param {Integer} id   WP Attachment ID of the image.
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +					button_text = $btn.attr( 'data-frame-button' ) || LLMS.l10n.translate( 'Select Image' );
```suggestion
					button_text = $btn.attr( 'data-frame-button' ) || LLMS.l10n.translate( 'Select Image' ),
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +			}
some golf...
```suggestion
			$remove.toggleClass( 'hidden', '' === id );
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on assets/js/llms-admin.js
> +				$remove  = $btn.hasClass( 'llms-image-field-remove' ) ? $btn : $btn.next( 'input.llms-image-field-remove' );
```suggestion
				$remove  = $btn.hasClass( 'llms-image-field-remove' ) ? $btn : $btn.next( 'button.llms-image-field-remove' );
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/abstracts/llms-abstract-engagement.php
> +		$src = LLMS_PLUGIN_URL . "/assets/images/optional_{$type}.png";
```suggestion
		$src = LLMS_PLUGIN_URL . "assets/images/optional_{$type}.png";
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/admin/post-types/meta-boxes/fields/llms.class.meta.box.image.php
> +	 *
```suggestion
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/admin/post-types/meta-boxes/fields/llms.class.meta.box.image.php
>  	 * @param array $_field Array containing information about field
```suggestion
	 * @param array $_field Array containing information about field.
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/admin/post-types/meta-boxes/fields/llms.class.meta.box.textarea.tags.php
>  	 * @param array $_field Array containing information about field
```suggestion
	 * @param array $_field Array containing information about field.
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/traits/llms-trait-singleton.php
> + * @package  LifterLMS_REST/Traits
```suggestion
 * @package LifterLMS/Traits
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/traits/llms-trait-singleton.php
> + * LLMS_REST_Trait_Singleton class..
```suggestion
 * LLMS_REST_Trait_Singleton class
```

2020-08-05 12:06 UTC, eri-trabiccolo commented on includes/traits/llms-trait-singleton.php
> +	 * @return obj instance of the LifterLMS_REST_API class.
```suggestion
	 * @return object Instance of the class.
```

2020-09-02 20:55 UTC, merged

2020-09-02 21:23 UTC, thomasplevy commented
I accidentally merged this into dev and had to rebase. Code review has been applied and reopening PR.