Refactor lesson navigation queries to reduce redundancy of code
gocodebox/lifterlms pull request #1318
Opened 2020-09-08 18:56 UTC by thomasplevy

## Description

Updates `LLMS_Lesson::get_next_lesson()` and `LLMS_Lesson::get_previous_lesson()` to use shared helper methods to locate sibling lessons.

The code for these two methods is nearly identical except for the sorting directions and compartors. There's a few logical differences between them but, overall, there's a of redundancy.

## How has this been tested?

+ Existing unit tests
+ Manual

## Screenshots 

## Types of changes

Code improvement

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-09-08 18:57 UTC, thomasplevy commented
@eri-trabiccolo for review when you return

2020-09-08 20:54 UTC, eri-trabiccolo commented
@thomasplevy
Alright, I will.
Maybe you want to already re-base it (see the two `@since [version]` in the `get_next_lesson()` method doc block).

2020-09-14 09:54 UTC, eri-trabiccolo requested changes

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +	 * @since [version] Use a numeric comparison for the previous position meta query.
```suggestion
	 * @since 4.4.2 Use a numeric comparison for the next position meta query.
```

This PR needs to be rebased to the current trunk.

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +	 * @since [version] Use a numeric comparison for the previous position meta query.
```suggestion
	 * @since 4.4.2 Use a numeric comparison for the previous position meta query.
```

This PR needs to be rebased to the current trunk, so I don't even know whether I should bother you with this kind of change request.

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +		if ( 0 === $curr_position && 'prev' === $direction ) {
```suggestion
		if ( 1 === $curr_position && 'prev' === $direction ) {
```
the minimum `order` value is 1 not 0.

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +				$sibling_position = $curr_position - 1;
If the section's `$curr_position === 1` (and looking for a prev lesson) we wouldn't need to run the query at all, right?

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +		$lesson = $this->get_sibling_lesson_query( $direction );
I'm not a fan of these "get_*_query" method names. The first time I read them I thought they would returned a WP_Query or even an SQL query.

What do you think if we turn `get_sibling_lesson_query` into `query_sibling_lesson` for example?

Also `get_sibling_section_query` makes me think we're going to retrieve a section not a lesson, what do you think about something like `query_sibling_lesson_from_adjacent_section`?

Filter names then should be changed accordingly.

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +
remove all these blank lines?
gh doesn't allow me to suggest it properly.

2020-09-14 09:54 UTC, eri-trabiccolo commented on includes/models/model.llms.lesson.php
> +	 *              Use strict comparisions where needed.
```suggestion
	 *              Use strict comparisons where needed.
```

2020-12-22 16:29 UTC, eri-trabiccolo commented
reworked (rebased) in https://github.com/gocodebox/lifterlms/pull/1467

2020-12-22 16:29 UTC, closed without merging