Attempt to sideload images during post generation
gocodebox/lifterlms pull request #1324
Opened 2020-09-09 23:47 UTC by thomasplevy

## Description

During course imports via the `LLMS_Generator`, parses the post_content of courses, lessons, quizzes, and access plans and sideload any `<img>` tags found within the content.

Per #1196 

## How has this been tested?

+ Added new unit tests
+ Existing unit tests

## Screenshots 

## Types of changes

+ Update

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-09-09 23:47 UTC, thomasplevy commented
@eri-trabiccolo for review when you return

2020-09-14 15:29 UTC, eri-trabiccolo requested changes
Aside from the minor (doc related) changes requested, I want to add some considerations.
I understand the main purpose of this PR, and for that very case (sample course import) works great, but I think we're missing something here.

1) I'm on site A and I'm going to export a course, that will be imported in the site B.
In my course's content there's an external image, e.g. it's located on amazon.
With this PR, when importing the course on site B that external image will be downloaded and added to the media library of site B.
I'm not sure this is what we want... 
(Note: the same will happen when cloning a course on the same site: cloning a lesson L whose content contains an external image will result in the external image downloaded and added to the media library).

Solution: We should reverse the approach here, e.g. we can parse the post content when "exporting" rather than on "importing", and create a _media_ field: an array of all the images (media in general) that should be downloaded when importing. In this case external images will not be added to this array.
(When cloning a post, on the other hand, we could just skip this array, but see the point 2 below for another consideration).

2) We know that this same code is used also when cloning our posts. At the moment we're not duplicating same site images, this might be technically _not perfect_. The thing is that we're not (and actually never did) taking into account "the post attachments", that as we know can have only one parent. So a clone of a lesson L1 that has M1 and M2 media attachments - images in its content, will be cloned to L2 which will still show M1 and M2 in the content but, of course, they won't be attached to it.

(weakly) related to 2) but not strictly to this PR, we always clone the post featured image, while I think we should do it only if the featured image is an attachment too, as in WP is totally possible to use the same image as featured image for many posts. This is actually something reported by one of our users too, now that I think about it:  HS-128125

2020-09-14 15:29 UTC, eri-trabiccolo commented on includes/class.llms.generator.php
> +		 * @param string         $post_status The default post status
```suggestion
		 * @param string         $post_status The default post status.
```

2020-09-14 15:29 UTC, eri-trabiccolo commented on includes/class.llms.generator.php
> +	 * URL of the image that has been sideloaded into the current site.
the array value is the attachment id.

2020-09-14 15:29 UTC, eri-trabiccolo commented on includes/class.llms.generator.php
> +	 * @var string[]
This is actually an associative array.

2020-09-14 15:29 UTC, eri-trabiccolo commented on includes/class.llms.generator.php
> +		$content  = $post->post->post_content;
```suggestion
		$content  = $post->get( 'content', true );
```
just to use our own api :D

2020-09-14 15:29 UTC, eri-trabiccolo commented on includes/class.llms.generator.php
> +		 */
```suggestion
		 * @param boolean        $enabled   Whether or not sideloading is enabled.
		 * @param LLMS_Generator $generator Generator instance.
		 */
```

2020-09-21 21:28 UTC, thomasplevy commented on includes/class.llms.generator.php
> +		$content  = $post->post->post_content;
Fine.

2020-09-21 21:29 UTC, thomasplevy commented
This PR has been integrated into #1341

2020-09-21 21:29 UTC, closed without merging