Introduce no_found_rows argument for LLMS_Database_Query
gocodebox/lifterlms pull request #1370
Opened 2020-10-12 15:26 UTC by eri-trabiccolo

## Description
per https://github.com/gocodebox/lifterlms/issues/933
starting point.

Additionally, as discussed here:
https://github.com/gocodebox/lifterlms/pull/1364#discussion_r501348592

I also started to get rid of `get_filter()` for that class and its extensions.

## How has this been tested?
new and old unit tests

## Screenshots 

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-10-12 21:01 UTC, thomasplevy requested changes
Functionally looks perfect, a few updates to the versions where filters were introduced.

I feel pretty confident that these were all introduced at the versions noted in my review.

2020-10-12 21:01 UTC, thomasplevy commented on includes/abstracts/abstract.llms.database.query.php
> +		 * @since unknown
Safe to assume that the introduction of the filter came with the introduction of the method since there haven't been any updates to the function since its introduction!

```suggestion
		 * @since 3.8.0
```

2020-10-12 21:01 UTC, thomasplevy commented on includes/abstracts/abstract.llms.database.query.php
> +		 * @since unknown
```suggestion
		 * @since 3.8.0
```

2020-10-12 21:01 UTC, thomasplevy commented on includes/abstracts/abstract.llms.database.query.php
> +			 * @since unknown
```suggestion
			 * @since 3.8.0
```

2020-10-12 21:01 UTC, thomasplevy commented on includes/abstracts/abstract.llms.database.query.php
> +		 * @since unknown
```suggestion
		 * @since 3.16.0
```

2020-10-12 21:01 UTC, thomasplevy commented on includes/abstracts/abstract.llms.database.query.php
> +		 * @since unknown
I'm confident enough with the introduction of this function with the initial method and not the 3.34.0 update.

```suggestion
		 * @since 3.8.0
```

2020-10-12 21:01 UTC, thomasplevy commented on tests/phpunit/unit-tests/abstracts/class-llms-test-abstract-database-query.php
> +<?php
!!!! <3

2020-10-12 21:03 UTC, merged

2020-10-13 14:29 UTC, eri-trabiccolo commented
you're right, thanks <3