Bug fix #1250
gocodebox/lifterlms pull request #1395
Opened 2020-10-19 14:34 UTC by imknight

## Description
add publicly_queryable checking on object to make sure it can be query from the front end.

Fixes #1250 

## How has this been tested?
login as admin, update email, message "Email updated" appear, without the view email with an invalid link

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ x] My code has been tested.
- [X ] My code passes all existing automated tests.
- [X ] My code follows the LifterLMS Coding & Documentation Standards.

2020-10-19 17:23 UTC, thomasplevy commented
@imknight thanks for your contribution, I believe this is perfect, @eri-trabiccolo thoughts?

2020-10-19 17:24 UTC, thomasplevy commented
I'm noting that this "needs tests" semantically but I think I'm okay shipping this without test coverage

2020-10-20 07:25 UTC, eri-trabiccolo requested changes
This works fine when you update a published (or publish a) post type, but doesn't take into account the draft creation/update, as the `$preview_link_html` (below) it's not set to an empty string.

Even more, as I _suggested_ in the issue's solution, if the post type is not publicly queryable we don't need to build any link at all.
So, this piece:
https://github.com/gocodebox/lifterlms/blob/eae925807d1c29f628d3b10ce1106d4691b9850f/includes/admin/class.llms.admin.post-types.php#L88-L96
could be turned into:
```php
			$permalink_html     = ''; 
			$preview_link_html  = '';

			if ( $obj->publicly_queryable ) {
				$permalink    = get_permalink( $post->ID );
				$preview_link = add_query_arg( 'preview', 'true', $permalink );

				$link_format = ' <a href="%1$s">%2$s</a>.';

				$permalink_html    = sprintf( $link_format, $permalink, sprintf( __( 'View %s', 'lifterlms' ), $name ) );
				$preview_link_html = sprintf( $link_format, $permalink, sprintf( __( 'Preview %s', 'lifterlms' ), $name ) );
			}
```

What do you think?

2020-10-20 14:11 UTC, imknight commented
> This works fine when you update a published (or publish a) post type, but doesn't take into account the draft creation/update, as the `$preview_link_html` (below) it's not set to an empty string.
> 
> Even more, as I _suggested_ in the issue's solution, if the post type is not publicly queryable we don't need to build any link at all.
> So, this piece:
> https://github.com/gocodebox/lifterlms/blob/eae925807d1c29f628d3b10ce1106d4691b9850f/includes/admin/class.llms.admin.post-types.php#L88-L96
> 
> 
> could be turned into:
> ```
> 			$permalink_html    = ''; 
> 			$preview_link_html = '';
> 
> 			if ( $obj->publicly_queryable ) {
> 				$permalink    = get_permalink( $post->ID );
> 				$preview_link = add_query_arg( 'preview', 'true', $permalink );
> 
> 				$link_format = ' <a href="%1$s">%2$s</a>.';
> 
> 				$permalink_html    = sprintf( $link_format, $permalink, sprintf( __( 'View %s', 'lifterlms' ), $name ) );
> 				$preview_link_html = sprintf( $link_format, $permalink, sprintf( __( 'Preview %s', 'lifterlms' ), $name ) );
> 			}
> ```
> 
> What do you think?

agree, it is more effective

2020-10-20 16:58 UTC, eri-trabiccolo requested changes
@imknight 
fine for me.
Can you please also add documentation changelog as per our standards?
file headers: https://github.com/gocodebox/lifterlms/blob/trunk/docs/documentation-standards.md#file-headers
meaning that this line: https://github.com/gocodebox/lifterlms/blob/4.6.0/includes/admin/class.llms.admin.post-types.php#L10
becomes:
` * @version [version]`
and that you add the changelog to the method you updated, so that this piece:
https://github.com/gocodebox/lifterlms/blob/4.6.0/includes/admin/class.llms.admin.post-types.php#L57-L64
becomes something like:
```php
	/**
	 * Customize post type messages.
	 *
	 * @since Unknown.
	 * @since 3.35.0 Fix l10n calls.
	 * @since [version] _HERE_THE_CHANGES_YOU_MADE_IN_THIS_PR_.
	 *
	 * @return array $messages
	 */
```

2020-10-21 14:17 UTC, imknight commented
updated documentation, let me know if anything I did wrongly

2020-10-21 15:53 UTC, thomasplevy requested changes

2020-10-21 15:53 UTC, thomasplevy commented on includes/admin/class.llms.admin.post-types.php
> +	 * @since [version] added publicly_queryable check for permalink and perview.
```suggestion
	 * @since [version] Added `publicly_queryable` check for permalink and preview.
```

2020-10-21 17:07 UTC, thomasplevy commented
@eri-trabiccolo I didn't test this but I think it's good to go after the documentation updates, right?

2020-10-21 18:01 UTC, eri-trabiccolo commented
@thomasplevy yes.

2020-10-21 18:05 UTC, merged