Improve the Importer success message
gocodebox/lifterlms pull request #1403
Opened 2020-10-21 23:04 UTC by thomasplevy

## Description

When doing final testing on generator improvements merged in from #1386 I noticed that as a result of adding new keys to the `LLMS_Generator` generated content property we now have a success message with duplicates since it lists the counts for *all* stats in the return.

I've made some changes and now, instead of listing our all of the generated content with numbers, the success message only contains two items:

1. Courses imported
2. Users imported

And instead of listing just a count of how many of each item were imported it creates a comma-separated list of anchors to the edit post/user admin page with the text of the anchor being the course title or user's display name.

This makes the success message, I hope, generally more usable instead of just relaying information.

I've never received any feedback about this but I would imagine that the first step after importing something is to have a look at it. This reduces the number of steps needed to perform that action.

We *lose* the counts but I don't think this really matters.

## How has this been tested?

+ Added New tests
+ Existing tests pass
+ Manually

## Screenshots 

## Types of changes

+ Updates

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-10-21 23:05 UTC, thomasplevy commented
@eri-trabiccolo I'd like to say this is the last one for this bit of refactoring but I have another one prepped too...

Thanks

2020-10-21 23:21 UTC, thomasplevy commented
@chrisbadgett can you have a look at the description and the screenshot and give me a yay or nay too please!

2020-10-22 17:08 UTC, eri-trabiccolo requested changes
I'm not against this change but... mmm
don't you think that the number of lessons/question/quizzes - especially when importing one course at a time - gave the user a nice feeling that everything went through? dunno - just a question.

2020-10-22 17:08 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.import.php
> +	 * @param string $type Object types. Either "post" or "user".
```suggestion
	 * @param string $type Object's type. Either "post" or "user".
```

2020-10-22 17:08 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.import.php
> +			$msg .= '<li>' . sprintf( __( 'Imported courses: %s', 'lifterlms' ), $this->get_generated_content_list( $generated['course'], 'post' ) ) . '</li>';
```suggestion
			// Translators: %s = comma-separated list of anchors to the imported courses.
			$msg .= '<li>' . sprintf( __( 'Imported courses: %s', 'lifterlms' ), $this->get_generated_content_list( $generated['course'], 'post' ) ) . '</li>';
```

2020-10-22 17:08 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.import.php
> +			$msg .= '<li>' . sprintf( __( 'Imported users: %s', 'lifterlms' ), $this->get_generated_content_list( $generated['user'], 'user' ) ) . '</li>';
```suggestion
			// Translators: %s = comma-separated list of anchors to the imported users.
			$msg .= '<li>' . sprintf( __( 'Imported users: %s', 'lifterlms' ), $this->get_generated_content_list( $generated['user'], 'user' ) ) . '</li>';
```

2020-10-22 17:08 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/admin/class-llms-test-admin-import.php
> + * @since [version] Test success message genration.
```suggestion
 * @since [version] Test success message generation.
```

2020-10-22 17:36 UTC, thomasplevy commented
> don't you think that the number of lessons/question/quizzes - especially when importing one course at a time - gave the user a nice feeling that everything went through? dunno - just a question.

I think it could give the user the feeling that it "worked" but I think showing a green success message with the name of the course(s) gives the same feeling.

I think I initially built it with the numbers so that *I could feel confident* that it worked but, lets say you've never used it before and you don't see all those numbers and you just see my screenshot, would you imagine feeling confident?

I'm not sure exactly but this feels like it does the same job to me.

I am sure that some experienced user will complain about the change but I'm not sure there's a really valid complaint there.

2020-10-23 18:56 UTC, merged