Feature/skip email
gocodebox/lifterlms pull request #1442
Opened 2020-11-25 21:54 UTC by jasonyingling

Meant to get to this sooner but things delayed me.

## Description
Added a filter and docblock to modify the value of the `$skip_email` variable.

Fixes #1411 

## How has this been tested?
Tested in by changing the filter to `true` with the following in functions.php on a local site running WordPress 5.5.3.

Also ran the `composer run-script tests-run -- --group LLMS_Person_Handler` test script.

```
function cbt_skip_email( $skip_email ) {
	return true;
}
add_filter( 'llms_skip_email', 'cbt_skip_email', 10, 1 );
```

## Screenshots 

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-11-30 18:19 UTC, thomasplevy requested changes

2020-11-30 18:19 UTC, thomasplevy commented on includes/class.llms.person.handler.php
> +				 * @since x.x.x
Per doc standards: https://github.com/gocodebox/lifterlms/blob/trunk/docs/documentation-standards.md#using-placeholders

```suggestion
				 * @since [version]
```

2020-11-30 18:19 UTC, thomasplevy commented on includes/class.llms.person.handler.php
> +				$skip_email = apply_filters( 'llms_skip_email', false );
As submitted I feel the hook name is too generic, something like this feels better to me:

```suggestion
				$skip_email = apply_filters( 'llms_skip_new_user_email_dupcheck', false );
```

2020-11-30 18:21 UTC, thomasplevy commented
@jasonyingling 

Thanks for your contribution here. 

A minor documentation issue that I'd have ignored had I not also wanted to request a change to the hook itself.

My thinking is that `llms_skip_email` is way too generic for what we're actually doing here with this variable, I've suggested a change above, thoughts?

2020-11-30 22:43 UTC, jasonyingling commented
@thomasplevy That's a much better name for it. I agree that was too generic. I was spinning wheels trying to best place it, but I think what you suggested works great.

2020-12-01 17:37 UTC, thomasplevy commented
Thanks @jasonyingling !

2020-12-01 17:40 UTC, merged