Admin notices CS & Test class
gocodebox/lifterlms pull request #1446
Opened 2020-11-30 20:48 UTC by thomasplevy

## Description

While starting to look into #1443 I fixed some CS issues in the `LLMS_Admin_Notices` class and added a test class so we can add test coverage for the (mostly) uncovered file.

## How has this been tested?

+ Manually

## Screenshots 

## Types of changes

+ CS, mostly
+ the only change that affects code execution is adding a strict comparator to `in_array()` which causes no issues because the notice ids are always strings anyway.

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-11-30 20:49 UTC, thomasplevy commented
@eri-trabiccolo mostly requesting your review to ensure I properly stylized the acronym 'CSS' (and like items) /winky face <3

2020-12-01 09:21 UTC, eri-trabiccolo requested changes

2020-12-01 09:21 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.notices.php
>  	 * Adds later for LLMS Settings screens to accommodate for settings that are updated later in the load cycle
```suggestion
	 * Adds later for LLMS Settings screens to accommodate for settings that are updated later in the load cycle.
```

2020-12-01 09:21 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.notices.php
>  	 * @return array
```suggestion
	 * @since 3.0.0
	 *
	 * @return array
```

2020-12-01 09:21 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.notices.php
> +	 * @param string $notice_id  Id of the notice.
```suggestion
	 * @param string $notice_id Id of the notice.
```

2020-12-01 09:21 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/admin/class-llms-test-admin-notices.php
> +	 * @since 4.7.0
```suggestion
	 * @since [version]
```

2020-12-01 17:43 UTC, merged