LifterLMS 5.0.0 (Working Branch)
gocodebox/lifterlms pull request #1478
Opened 2021-01-05 19:42 UTC by thomasplevy

2021-01-27 13:07 UTC, eri-trabiccolo requested changes
Just something I noticed while testing the forms. :D

2021-01-27 13:07 UTC, eri-trabiccolo commented on languages/states.php
> +Countries with an empty array have no states.
```suggestion
 * Returns a multi-dimensional array of countries and country states (or provinces / regions) and their respective codes.
 * Countries with an empty array have no states.
```

2021-01-27 13:07 UTC, eri-trabiccolo commented on languages/states.php
> + * @version [vesion]
```suggestion
 * @since [version]
 * @version [version]
```

2021-01-27 13:07 UTC, eri-trabiccolo commented on languages/states.php
> +		'88' => __( 'Sardinia', 'lifterlms' ),
This is a "problem".
The list here is for italian's regions.
In Italy we don't use them when specifying a billing (or even shipping) address. We use to specify what we call Provinces. Example.
I'm in Pinerolo (city/town) which is in province of Turin (province) in the Piedmont region.
Naples is both a city/town and a province in the Campania region.

When I specify my address I say:
Pinerolo (TO): TO is the italian province code for Turin.
This is the actual list we should use for italian provinces:
https://github.com/woocommerce/woocommerce/blob/e3b69b901143de3c42d90b9d4bdc97a8821133e2/i18n/states.php#L645

Maybe we should double check (compare with wc) other countries' states/provinces too...

2021-01-27 13:07 UTC, eri-trabiccolo commented on languages/countries.php
> + * @version [vesion]
```suggestion
 * @since [version]
 * @version [version]
```

2021-01-27 15:50 UTC, thomasplevy commented on languages/states.php
> +Countries with an empty array have no states.
Thank you, fixed in https://github.com/gocodebox/dev-tools/commit/390f7625404f4367267957a71b32e111f3c07ad0#diff-2e062f03cfac811baea27d27f0fc3b2b13174df3f095b88fce4c90766ca72d47R184

2021-01-27 15:51 UTC, thomasplevy commented on languages/states.php
> + * @version [vesion]
Fixed in https://github.com/gocodebox/dev-tools/commit/629cd8cc54952373299170728323b77228456c50

2021-01-27 15:51 UTC, thomasplevy commented on languages/countries.php
> + * @version [vesion]
https://github.com/gocodebox/dev-tools/commit/629cd8cc54952373299170728323b77228456c50

2021-01-27 16:05 UTC, eri-trabiccolo commented on languages/states.php
> +Countries with an empty array have no states.
Ohhh sorry, I forgot that.

2021-04-14 20:20 UTC, eri-trabiccolo reviewed
Jeez the suspance created by this commit message is going to kill me... 😜

2021-06-15 23:05 UTC, merged