Fix draft course errors on course builder
gocodebox/lifterlms pull request #1514
Opened 2021-02-03 23:07 UTC by thomasplevy

## Description

Fixes #1508 

## How has this been tested?

+ Manually

## Types of changes
+ Bug fix (realistically this is a hack because backbone is a mess and I don't understand why this is happening but it's fixed with this pr)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-02-03 23:07 UTC, thomasplevy commented on assets/js/builder/Models/Section.js
> +		 * @since 3.16.0
```suggestion
		 * @since [version]
```

2021-02-04 08:54 UTC, eri-trabiccolo requested changes
Doc and golf changes requested.
Works fine.

2021-02-04 08:54 UTC, eri-trabiccolo commented on assets/js/builder/Models/Lesson.js
> + * @since  3.13.0
```suggestion
 * @since 3.13.0
```

2021-02-04 08:54 UTC, eri-trabiccolo commented on assets/js/builder/Models/Lesson.js
> +		 * @return obj
```suggestion
		 * @return {Object}
```

2021-02-04 08:54 UTC, eri-trabiccolo commented on assets/js/builder/Models/Section.js
> +		 * @return obj
```suggestion
		 * @return {Object}
```

2021-02-04 08:54 UTC, eri-trabiccolo commented on assets/js/builder/Models/Section.js
> +			}
```suggestion
			// When working with an unsaved draft course the parent isn't properly set on the creation of a section.
			if ( ! this.get_parent() ) {
				this.set_parent( window.llms_builder.CourseModel );
			}
```
golf

2021-02-04 18:12 UTC, merged