Issue/1010
gocodebox/lifterlms pull request #1542
Opened 2021-02-23 17:44 UTC by eri-trabiccolo

## Description
Fixes #1010 

@thomasplevy The reason I'm fixing this is that, despite what #1010 says, we got too many reports about this. They're not massive, but every now and then our support team has to deal with a customer reporting this, then asking _us_ what's that error etc. Let's fix this so that we can save time/resources :D. 

## How has this been tested?
Manually and with new unit tests.

## Screenshots 
n/a

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-02-24 15:42 UTC, thomasplevy commented
@eri-trabiccolo thanks for this, I reviewed briefly, I'll do some testing and full review later.

2021-02-24 20:04 UTC, thomasplevy requested changes
@eri-trabiccolo

I see one minor issue, see screencap:

![Screenshot_2021-02-24_13-02-23](https://user-images.githubusercontent.com/1290739/109058766-a0d39d80-76a0-11eb-8bbb-f2fb9506f47d.png)

Pretty minor but should be easy enough to clean up really quick. I'm okay if we don't get into adding test cases for this particular thing but while we're looking at it that would also help make it very obvious that this student doesn't exist anymore instead of having a dead link

Secondly: my feedback is all about helper functions in the testing library. I don't actually care if you don't want to rewrite the tests to use the helpers but I wanted you to know they exist.

2021-02-24 20:04 UTC, thomasplevy commented on tests/phpunit/unit-tests/admin/post-types/meta-boxes/class-llms-test-meta-box-order-enrollment.php
> +		$this->assertEquals( 'Cannot manage enrollment status for anonymized orders.', ob_get_clean() );
A test helper exists to change this to the suggestion

Source: https://github.com/gocodebox/lifterlms-tests/blob/a812e7be616331dc1a1acca2cba8a78b8dd04539/framework/traits/trait-llms-unit-test-assertions-output.php#L57-L71

```suggestion
		$this->assertOutputEquals( 'Cannot manage enrollment status for anonymized orders.', array( $this->metabox, 'output' ) );
```

2021-02-24 20:04 UTC, thomasplevy commented on tests/phpunit/unit-tests/admin/post-types/meta-boxes/class-llms-test-meta-box-order-enrollment.php
> +		ob_start();
Like above, another helper: https://github.com/gocodebox/lifterlms-tests/blob/a812e7be616331dc1a1acca2cba8a78b8dd04539/framework/traits/trait-llms-unit-test-assertions-output.php#L42-L55

2021-02-24 20:04 UTC, thomasplevy commented on tests/phpunit/unit-tests/admin/post-types/meta-boxes/class-llms-test-meta-box-order-enrollment.php
> +		ob_start();
can use helper

2021-02-24 20:04 UTC, thomasplevy commented on tests/phpunit/unit-tests/admin/post-types/meta-boxes/class-llms-test-meta-box-order-enrollment.php
> +		ob_start();
https://github.com/gocodebox/lifterlms-tests/blob/a812e7be616331dc1a1acca2cba8a78b8dd04539/framework/traits/trait-llms-unit-test-assertions-output.php#L82

2021-02-25 09:13 UTC, eri-trabiccolo commented
@thomasplevy done

2021-02-25 19:37 UTC, thomasplevy commented
@eri-trabiccolo looks good, I noticed that the orders post table list has the same problem as the order metabox, I've just updated this locally instead of making you checkin on this again tomorrow. I'm going to merge into dev with my changes.

Thanks!

2021-02-25 19:37 UTC, merged