Don't process non-existent courses during course data processing
gocodebox/lifterlms pull request #1599
Opened 2021-04-16 20:15 UTC by thomasplevy

## Description

Fixes #1598 

## How has this been tested?

+ New + existing phpunit tests

## Screenshots 

## Types of changes
+ Bugfix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-04-16 20:53 UTC, pondermatic commented
This fix looks great!

2021-04-19 09:02 UTC, eri-trabiccolo requested changes
fine for me, except for the minor changes requested in the tests.

2021-04-19 09:02 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php
> +		wp_delete_post( $tests[0], true );
```suggestion
```
we already delete this post at line 431, right?

2021-04-19 17:56 UTC, thomasplevy commented on tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php
> +		wp_delete_post( $tests[0], true );
actually the issue is the deletion on 431, I only want to be testing that a deleted course and the other's should exist before running the test otherwise I'm testing the same thing (essentially) twice.

Either way, thanks for noticing

2021-04-19 17:58 UTC, merged