Issue/1652
gocodebox/lifterlms pull request #1654
Opened 2021-06-09 17:45 UTC by eri-trabiccolo

## Description
**wip
Opened to simplify the review/feedback (e.g. on the admin notice) process**
 
Fixes #1652 

Also:
1) we need to add the proper link to the announcement post when ready
2) we need to ad the proper link to the documentation when ready

## How has this been tested?
Manually and new unit tests

## Types of changes
Bug fix (non-breaking change which fixes an issue)/New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-06-11 21:19 UTC, thomasplevy requested changes
Overall good, some notes here

And after reviewing what it actually looks like I think we can drop the link to the technical docs (we'll have a link to that in the blog post)

With only two options I think having a main action and a secondary action is satisfactory

Final thought: if someone clicks "getting started" i think the notice should be dismissed, we should be able to do that pretty easily by adding a nonce link that hooks into the existing actions to hide dismiss/remove notices

2021-06-11 21:19 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +	set_transient( 'llms_update_500_autoload_off_legacy_options', 'complete', DAY_IN_SECONDS );
I don't think we need a transient here, updating 3 options in a single query shouldn't require pagination, right?
```suggestion
```

2021-06-11 21:19 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +
```suggestion
```

Like above, should be able to remvoe this, yes?

2021-06-11 21:19 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +			'dismiss_for_days' => 730, // @TODO: there should be a "forever" setting here.
Based on the way this message is displayed, it'll be added and once dismissed never added again (unless this function is called)

So we can actually set `dismiss_for_days` to `0` so that data is set to allow it to be re-displayed later.

```suggestion
			'dismiss_for_days' => 0,
```

2021-06-11 21:19 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +				'<a href="' . add_query_arg(
```suggestion
				'<a class="button-primary" href="' . add_query_arg(
```

2021-06-11 21:19 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +				'<a href="" target="_blank" rel="noopener">',
```suggestion
				'<a class="button" href="" target="_blank" rel="noopener">',
```

2021-06-11 21:23 UTC, thomasplevy commented on includes/functions/updates/llms-functions-updates-500.php
> +		basename( __FILE__, '.php' ),
```suggestion
		'v500-welcome-msg',
```
Or something to that effect.

2021-06-14 07:21 UTC, eri-trabiccolo commented on includes/functions/updates/llms-functions-updates-500.php
> +	set_transient( 'llms_update_500_autoload_off_legacy_options', 'complete', DAY_IN_SECONDS );
Yup, you're right

2021-06-14 08:24 UTC, eri-trabiccolo commented
> Final thought: if someone clicks "getting started" i think the notice should be dismissed, we should be able to do that pretty easily by adding a nonce link that hooks into the existing actions to hide dismiss/remove notices

@thomasplevy 

It actually isn't that simple because you know the message is saved in the db, and the nonce URL will be part of the message... Additionally we'll have two different nonces one for the get started link and another one for the dismiss icon link, with the latter that will win. Meaning that the nonce will be invalid for the get started link.

What do you think if we filter the notice message, a filter param will be the nonce.
The idea is that we add the notice with the Get Started button having a "merge code" in its href, so that we can replace it with the same nonce as the dismiss icon.

Let me know, if you "like" it or you have alternatives (maybe js?).

2021-06-14 17:35 UTC, thomasplevy commented
@eri-trabiccolo mmm you're right. Let's leave it as is then and when users want the message gone they hit the "X" in the right corner and it's gone.

2021-06-14 17:50 UTC, merged

2021-06-14 17:52 UTC, thomasplevy commented
Modified this slightly to remove the "or" between the buttons and switch the text CTA to a secondary (default) button

Thanks @eri-trabiccolo