BUild a tool to help identify orders potentially affected by payment plan changes in 5.3.0
gocodebox/lifterlms pull request #1760
Opened 2021-08-26 18:26 UTC by thomasplevy

## Description

Building on #1744

Adds a (conditionally loaded) tool to identify orders potentially affected by the changes to how an limited-billing recurring order is ended

Prior to #1744 these orders ended by a calculated date, now they end based on the number of successful (and refunded) payments.

This tool generates a CSV of affected active and on-hold orders with a billing length of at least one which meet one of the following criteria:

1. The order contains at least one refund
2. The order is marked as "ended" and has fewer successful transactions than the expected number (the billing length)

This tool does not take any actual action on the orders, it just generates a report that an admin should review and do what they like with. The main concern would be orders that ended incorrectly and need additional billing to be added. Admins can visit the order screen and update the remaining payments via the new interface should they disagree with the new rules.

This PR additionally introduces a pluggable wrapper for `exit()` that has been redefined in `lifterlms/lifterlms-tests` so that we can easily test methods that `exit()`.

It also updates other admin tool testing classes to consolidate redundant tests (mainly testing methods like `get_text()`...

And I moved all the pluggable wrappers from `includes/llms.functions.core.php` to their own function file.

## TODO

- [x] A piece of documentation needs to be written about this and then the tool description's link should be updated once the link exists. 

## How has this been tested?

+ Manually
+ New tests

## Screenshots 

## Types of changes
+ New feature

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-08-27 13:41 UTC, eri-trabiccolo requested changes

2021-08-27 13:41 UTC, eri-trabiccolo commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +			}
```suggestion
```
Don't see how could `$order` be a falsy or not an LLMS_Order, given how `llms_get_post()` works

2021-08-27 13:41 UTC, eri-trabiccolo commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +	 *
copypasta

2021-08-27 13:41 UTC, eri-trabiccolo commented on includes/functions/llms-functions-wrappers.php
> +		call_user_func( $func, $location, $options['status'] );
```suggestion
		$func( $location, $options['status'] );
```
:D

2021-08-27 13:41 UTC, eri-trabiccolo commented on includes/functions/llms-functions-wrappers.php
> +	 * @param string $location Full URL to redirect to
```suggestion
	 * @param string $location Full URL to redirect to.
```

2021-08-27 13:41 UTC, eri-trabiccolo commented on includes/functions/llms-functions-wrappers.php
> +	 *     @type bool $safe   If true, use `wp_safe_redirect()` otherwise use `wp_redirect()`. Default: `true`.
```suggestion
	 * @param array  $options  {
	 *     Optional. Array of options. Default is empty array.
	 *
	 *     @type int  $status HTTP status code of the redirect. Default: `302`.
	 *     @type bool $safe   If true, use `wp_safe_redirect()` otherwise use `wp_redirect()`. Default: `true`.
	 * }
```

2021-08-27 14:08 UTC, eri-trabiccolo commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +			$link = get_edit_post_link( $id );
```suggestion
			$link = get_edit_post_link( $id, 'raw' );
```
or anything different from 'display', which is the default value, which will turn & into &amp; generating something like:
https://mywp.loc/wp-admin/post.php?post=1389&amp;action=edit
which is a "bad" link.
That said, the WordPress doc says:
Optional. How to output the '&' character. Default '&amp;'.
https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/link-template.php#L1433
but the generated html doc:
(string) (Optional) How to output the '&' character. Default '&'.
so I guess it's not your fault :P
cc @pondermatic maybe something you want to "consider" for your work on the docblocks?

2021-08-27 18:34 UTC, thomasplevy commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +			}
yea, you're right. Habit from using the function when we don't exactly know what the input is (as we do in this case)

2021-08-28 00:03 UTC, thomasplevy commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +			$link = get_edit_post_link( $id );
Yes, you're correct about this. Nice.

I also noticed the unit tests weren't actually testing anything with relation to this due to having no logged in user. Whoop. Fixed that too!

2021-08-28 00:04 UTC, thomasplevy commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +	 *
always <3

2021-08-28 00:06 UTC, thomasplevy commented
@eri-trabiccolo noticed that the lookup for possibly affected orders would also include orders made *after* the upgrade. I've added an EXISTS check on the removed meta property (`_llms_date_billing_end`) to ensure that the tool doesn't pick up orders created *after* the upgrade. These newer orders shouldn't be included because A) the bug is fixed and payments won't be missed and B) If someone refunds the order moves to *refunded* and then they have to switch it back to active at which point they'd be aware of the number of remaining payments and change accordingly. 

Does my logic seem sound on this to you? This is primarily why I'm requesting a re-review.

2021-08-30 08:08 UTC, eri-trabiccolo requested changes
Looks good.
The only "missing" thing is a way to exclude already reviewed orders.
Meaning that I run the tool and it finds 10 orders to be reviewed, then I review them and decide they're all fine. Back on Tools, and run it again - it'll find the same orders.
Not a big deal I guess.

2021-08-30 08:08 UTC, eri-trabiccolo commented on includes/admin/tools/class-llms-admin-tool-limited-billing-order-locator.php
> +	 * Generate the CSV file an server it as a downloadable attachment
```suggestion
	 * Generate the CSV file an serve it as a downloadable attachment
```

2021-08-30 17:48 UTC, thomasplevy commented
@eri-trabiccolo any thoughts on the ideal workflow for removing an order from a report... You're right that there's no way to do this and I hadn't thought about that... Other than building a UI to "mark as okay" somewhere on the view order admin ui I don't really have any thoughts on what to do here... Ideally a user would review this once only and never need to again but I don't know how to get rid of it once they're happy in that case...

Any thoughts?

2021-08-30 18:39 UTC, eri-trabiccolo commented
> @eri-trabiccolo any thoughts on the ideal workflow for removing an order from a report... You're right that there's no way to do this and I hadn't thought about that... Other than building a UI to "mark as okay" somewhere on the view order admin ui I don't really have any thoughts on what to do here... Ideally a user would review this once only and never need to again but I don't know how to get rid of it once they're happy in that case...
> 
> Any thoughts?

I thought about:
1) save the "is reviewed" in a order post meta, like a checkbox, which updates via ajax - so it doesn't require a submit button to be clicked. But this should appear only on the ones which need to be reviewed...
Maybe clumsy.
2) buttons next to the tool:
- mark all as reviewed: adds a not autoloaded option
- once this option is set ideally you won't see the tool again (we can think about having a constant to make the tool appear again...). Maybe still clumsy...
What do you think?

2021-08-30 18:58 UTC, thomasplevy commented
I think this means writing a lot of code and tests and further delaying the release of a bugfix that should have been shipped a week ago at least...

What if we update language of the tool to say "You can only perform this action once" and then set a non-autoloading option after the CSV is downloaded which hides the tool (forever)?

This probably isn't a good solution because someone will inevitably lose the CSV or something will go wrong and the option will get set but the CSV won't be downloaded or they'll download it and have incorrect file permissions set on their PC and they won't be able to access it or something...

If we don't touch this at all... just the leave the tool as is and ship, what happens? Users review and they say "Everything's good" but the tool still shows up... does anyone go there and get upset about this? If they do we tell them "You already reviewed it, it's okay" and they say "But I don't want to the see the tool anymore, it's confusing" and we say "We've explained what happened, it doesn't go away, you'll just have to ignore it"

Is this acceptable? I don't know.... I really don't want to write and test anymore code for this though. I want to ship the bugfix

2021-08-30 19:22 UTC, eri-trabiccolo commented
@thomasplevy 
None of the solutions is the best, so yeah let's go with the current implementation, and yeah we'll tell people it's fine it shows up.

2021-08-30 22:02 UTC, merged