Add `LLMS_Abstract_Options_Data` to `LLMS_Payment_Gateway` abstract
gocodebox/lifterlms pull request #1761
Opened 2021-08-26 23:47 UTC by thomasplevy

## Description

Improves a gateway's ability to interact with it's own options primarily by adding the `set_option()` method.

## How has this been tested?

+ Manually
+ New tests

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-08-27 08:10 UTC, eri-trabiccolo requested changes

2021-08-27 08:10 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.payment.gateway.php
> +	 * @param string $secure_key Secure option name / key, eg: "TITLE".
```suggestion
	 * @param string $secure_key Optional. Secure option name / key, eg: "TITLE". Default is `false`.
```

2021-08-27 08:10 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.payment.gateway.php
> +		return isset( $this->$unprefixed ) ? $this->$unprefixed : '';
Does this mean that we always return an empty string if `$this->$unprefixed` is not set, whatever is the passed default value to `get_option()`? Is this intended?

2021-08-27 19:00 UTC, thomasplevy commented on includes/abstracts/abstract.llms.payment.gateway.php
> +	 * @param string $secure_key Secure option name / key, eg: "TITLE".
We've been doing this a bit recently (I think I started it) but I realized just now that we are creating redundant text on the developer site when we do this.

Have a look at this generated doc: https://developer.lifterlms.com/reference/functions/llms_get_post/

The "Optional" and "Default Value" are automatically added to the generated doc without the need for us to write it. It can be inferred and we don't need to write it.

If we write the same doc this way it'll end up saying optional and default value twice as a result of the automatically added stuff.

So... we should stop writing docs like this to prevent duplications on the doc site... I didn't realize this was auto-added...

2021-08-27 19:09 UTC, thomasplevy commented on includes/abstracts/abstract.llms.payment.gateway.php
> +		return isset( $this->$unprefixed ) ? $this->$unprefixed : '';
It's not exactly intentional but it is a result of poor foresight (by me) when I introduced `LLMS_Payment_Gateway::get_option()`.

The *current* version of the class *requires* every option to be defined as a class variable. If you want to have `llms_gateway_{id}_title` as an option, then you need to define `public $title = 'default val'` on the gateway class.

The current version will throw an error if the option isn't defined: 

https://github.com/gocodebox/lifterlms/blob/8c913be8492b8216f8657ae2864ac0411c8d8700/includes/abstracts/abstract.llms.payment.gateway.php#L724-L736

So the change I'm introducing is to return an empty string if the variable isn't set on the class.

If you call `get_option()` directly you can pass in a default value and this won't run as the callback is only hooked (and unhooked) when calling `LLMS_Abstract_Options_Data::get_option()` -- https://github.com/gocodebox/lifterlms/blob/8c913be8492b8216f8657ae2864ac0411c8d8700/includes/abstracts/llms.abstract.options.data.php#L60-L66

So... this *doesn't change* any existing gateways that are already working "as expected" by having a default value defined as a var on the class but enables gateways to remove these variables (if they want) and to define their own autloader of default values if they choose.

Ideally there's more changes to make here:

The default value should *automatically be loaded from the settings array* and the secure key option should be automatically used (instead of requiring it to be passed into get_option()` but I haven't figured out if that's truly necessary yet...

Mostly: I have built and worked on all our gateways and everytime I work on one I'm mad that in order to *update an option programatically* I have to write : `update_option( $this->get_option_name( ... ), val )`

2021-08-27 19:10 UTC, thomasplevy commented on includes/abstracts/abstract.llms.payment.gateway.php
> +		return isset( $this->$unprefixed ) ? $this->$unprefixed : '';
At least this was my intention... I think this works as I intended, right? Do you see a logical flaw or error here that I'm missing?

2021-08-27 19:12 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.payment.gateway.php
> +	 * @param string $secure_key Secure option name / key, eg: "TITLE".
Riiight. <3
You know. WP does it here and there. Ok let's stop.

2021-08-27 19:40 UTC, thomasplevy commented on includes/abstracts/abstract.llms.payment.gateway.php
> +	 * @param string $secure_key Secure option name / key, eg: "TITLE".
I'm actually not sure I'm right about it creating duplicates... I'm digging through code and it's a waste of my time right now... I don't want duplicated content on the frontend but it looks the WP core doesn't have duplicates when they do this so I can't explain the source or reasoning here... it's possibly an upstream feature coming from phpdocumentor itself... maybe if it detects default and optional it doesn't include it somehow... I'm not sure... Either way I think we're fine and I'm not going to change anything at this moment...

2021-08-30 08:13 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.payment.gateway.php
> +		return isset( $this->$unprefixed ) ? $this->$unprefixed : '';
I think it works as expected yeah. Thanks for the explanation.

2021-08-30 08:14 UTC, eri-trabiccolo approved these changes

2021-08-30 18:15 UTC, merged