#1325 - added action doc block
gocodebox/lifterlms pull request #1813
Opened 2021-10-04 05:13 UTC by chetansatasiya

## Description

Fixes #

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

2021-10-04 15:11 UTC, pondermatic requested changes
Great job on the parameters!

2021-10-04 15:11 UTC, pondermatic commented on includes/class.llms.voucher.php
> +				 * @since 2.0.0
This hook first appeared in the [2.2.1](https://github.com/gocodebox/lifterlms/blob/2.2.1/includes/class.llms.voucher.php#L255) release.

Please add:
* `@since 3.24.1 Added $voucher_title parameter.`
* `@since 3.27.0 Changed $voucher_title to $voucher_code to fix undefined property notice.`

I found these changes in:
* [changelog](https://github.com/gocodebox/lifterlms/blob/trunk/CHANGELOG.md)
* [git blame 1](https://github.com/gocodebox/lifterlms/blame/5f2b0210faa32c451d31ea91f6847025dda13984/includes/class.llms.voucher.php#L338)
* [git blame 2](https://github.com/gocodebox/lifterlms/blame/0c2523f3a53d70d19b8e6d14bee40e4cf0d7f893/includes/class.llms.voucher.php#L311)
* [git blame 3](https://github.com/gocodebox/lifterlms/blame/052a3f2fe44a60b6f41429e5bbe4497aa5f53b9c/includes/class.llms.voucher.php#L311)

2021-10-04 15:11 UTC, pondermatic commented on includes/class.llms.voucher.php
> +				 * @link  https://github.com/gocodebox/lifterlms/issues/1325
In this case, the link to the issue is not needed because the issue is about the missing DocBlock and not about a bug. I appreciate the effort though!

2021-10-06 05:35 UTC, chetansatasiya commented on includes/class.llms.voucher.php
> +				 * @since 2.0.0
@pondermatic Added 👍

2021-10-06 05:37 UTC, chetansatasiya commented on includes/class.llms.voucher.php
> +				 * @link  https://github.com/gocodebox/lifterlms/issues/1325
Removed 👍

2021-10-06 15:53 UTC, pondermatic approved these changes

2021-10-07 22:38 UTC, merged