#1817 - added a filter to modify the user id
gocodebox/lifterlms pull request #1819
Opened 2021-10-06 05:51 UTC by chetansatasiya

## Description

Fixes #

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

2021-10-07 22:53 UTC, thomasplevy requested changes
Thanks for this @chetansatasiya, a few notes to improve the documentation:

2021-10-07 22:53 UTC, thomasplevy commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * @since 5.3.4
A build step will replace the `[version]` placeholder with the actual version number which we'll determine later. This may be included in 5.3.4 or maybe 5.4.0...

```suggestion
		 * @since [version]
```

2021-10-07 22:53 UTC, thomasplevy commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * Filter to modify the User id instead of current loggedin user id.
spelling: 
```suggestion
		 * Filter to modify the user id instead of current logged in user id.
```

2021-10-07 22:53 UTC, thomasplevy commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * @since 5.3.4
```suggestion
		 * @since [version]
```

2021-10-07 22:53 UTC, thomasplevy commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * Filter to modify the User id instead of current loggedin user id.
spelling: 
```suggestion
		 * Filter to modify the user id instead of current logged in user id.
```

2021-10-07 22:53 UTC, thomasplevy commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		$user_id = apply_filters( 'llms_lesson_in_complete_user_id', get_current_user_id() );
It's "incomplete" not "in complete" so separation via underscore is incorrect.

```suggestion
		$user_id = apply_filters( 'llms_lesson_incomplete_user_id', get_current_user_id() );
```

2021-10-08 05:17 UTC, chetansatasiya commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * @since 5.3.4
Done 👍

2021-10-08 05:17 UTC, chetansatasiya commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * Filter to modify the User id instead of current loggedin user id.
Done 👍

2021-10-08 05:17 UTC, chetansatasiya commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * @since 5.3.4
Done 👍

2021-10-08 05:17 UTC, chetansatasiya commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		 * Filter to modify the User id instead of current loggedin user id.
Done 👍

2021-10-08 05:17 UTC, chetansatasiya commented on includes/controllers/class.llms.controller.lesson.progression.php
> +		$user_id = apply_filters( 'llms_lesson_in_complete_user_id', get_current_user_id() );
Done 👍

2021-10-08 16:59 UTC, merged

2021-10-08 16:59 UTC, thomasplevy commented
Thanks @chetansatasiya !