Rename llms_certificate and llms_my_certificate post type slugs
gocodebox/lifterlms pull request #1855
Opened 2021-11-11 20:08 UTC by thomasplevy

## Description

Based on @eri-trabiccolo's proposed solution here: https://github.com/gocodebox/lifterlms/pull/1771#issuecomment-966107495

Instead of storing an option and putting a lifespan on the redirect I've opted to handle requests to the old URL and redirect them. If we store an option based on whether or not any shared certificates exist we run into an issue where bookmarks *might exist* for users that aren't sharing them (but have them saved somewhere for their own private purposes). 

This just performs a pretty safe redirect when a 404 is encountered, the URL contains `/my_certificate/` (or the equivalent transation), and an earned certificate exists for the slug (parsed from the url).

This should just do the job. In the scenario where someone has changed the slug via a filter this *will not work* but in that scenario we wouldn't want it to anyway since it's already been customized.

## How has this been tested?

+ Manually 
+ New PHPUnit tests

## Screenshots 

## Types of changes
+ New feature

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2021-11-11 20:16 UTC, eri-trabiccolo reviewed
I will better review this tomorrow, but this check on is_404 looks pretty smart... <3

2021-11-12 08:41 UTC, eri-trabiccolo requested changes
The only other thing to consider here is that potentially `maybe_redirect_certificate()` matches also `'https://www.example.com/something/my_certificate/something'`, and for that `$slug = str_replace( $old, '', wp_parse_url( $url, PHP_URL_PATH ) );` will return
`/somethingsomething`.
But I think you already considered this and evaluated it as too much of an edge case also because we already check for if `is_404` so we don't break anything. Right?

2021-11-12 08:41 UTC, eri-trabiccolo commented on includes/class.llms.query.php
> +		if ( $wp_query->is_404() && str_contains( $url, $old ) ) {
`str_contains()` requires PHP 8+
```suggestion
		if ( $wp_query->is_404() && false !== strpos( $url, $old ) ) {
```

2021-11-15 16:44 UTC, thomasplevy commented
> The only other thing to consider here is that potentially `maybe_redirect_certificate()` matches also `'https://www.example.com/something/my_certificate/something'`, and for that `$slug = str_replace( $old, '', wp_parse_url( $url, PHP_URL_PATH ) );` will return `/somethingsomething`. But I think you already considered this and evaluated it as too much of an edge case also because we already check for if `is_404` so we don't break anything. Right?

This should handle this edge case: https://github.com/gocodebox/lifterlms/pull/1855/commits/b9156e46a2d783303eee8edad272c3bbcb891e1f

2021-11-16 16:10 UTC, merged