Adding Flex Cols to fix quiz picture question spacing
gocodebox/lifterlms pull request #1970
Opened 2022-02-04 16:56 UTC by nrherron92

## Description
Modifying grid scss core to add .llms-flex-cols class to utilize flexbox.

## How has this been tested?
I tested it manually (after running npm run build:styles)

## Types of changes
added .llms-flex-cols class
updated multiple choice picture quiz template

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

2022-02-04 17:11 UTC, thomasplevy commented
@nrherron92 you based this off dev-600 so switched the base there. That means this will have to wait until 6.0 is released. We can rebase off dev if we feel this needs a release sooner. At this moment I don't have anything else planned for release prior to 6.0 though.

2022-02-04 17:16 UTC, nrherron92 commented
It can wait (though that wasn't intentional) there's a workaround i can give the user in the meantime! Sorry about that!

2022-02-07 15:47 UTC, eri-trabiccolo commented on assets/scss/_includes/_grid.scss
> +
```suggestion
```
no need to add a new line here.

2022-02-07 15:47 UTC, eri-trabiccolo commented on assets/scss/_includes/_grid.scss
> +   		flex: 0 1 auto;
This is the initial `flex` value, so we could omit it here, although I'm more inclined to add it as you did, just to be a little bit more sure the cols are not inheriting a different `flex` value from the themes.

2022-02-07 15:49 UTC, eri-trabiccolo commented
This is the initial flex value, so we could omit it here, although I'm more inclined to add it as you did, just to be a little bit more sure the cols are not inheriting a different flex value from the themes.
https://github.com/gocodebox/lifterlms/pull/1970/files#diff-590a9c43554f64d68701baa82f21ffa05b8d400e60f61ff447125ad1ae8abf83R31

Can you please delete this line? 
https://github.com/gocodebox/lifterlms/pull/1970/files#diff-590a9c43554f64d68701baa82f21ffa05b8d400e60f61ff447125ad1ae8abf83R21
No need to add a new one there :D

Aside for this it looks great to me! Thanks <3

2022-02-07 15:50 UTC, eri-trabiccolo requested changes
https://github.com/gocodebox/lifterlms/pull/1970#issuecomment-1031618957

2022-02-09 21:41 UTC, thomasplevy commented
I'm going to rebase this against `dev` so we can ship with the 5.x release I'm prepping.

2022-02-09 22:03 UTC, thomasplevy commented
Closing in favor of #1988

2022-02-09 22:05 UTC, closed without merging