Adjust certificate "mini cert" to be a placeholder as opposed to containing actual certificate content
gocodebox/lifterlms pull request #1973
Opened 2022-02-04 20:05 UTC by thomasplevy

## Description

Closes #1950

## How has this been tested?

+ Manually

## Screenshots 

https://user-images.githubusercontent.com/1290739/152595848-b54fc890-87a8-4bad-91ff-8156e4e63bd8.mp4

2022-02-08 10:47 UTC, eri-trabiccolo requested changes
looks good overall!

2022-02-08 10:47 UTC, eri-trabiccolo commented on assets/scss/frontend/_llms-notifications.scss
> +						p { margin-bottom: 0; }
```suggestion
					.llms-mini-cert--mock-line {
						border-radius: 2px;
						height: 8px;
						background: #b0b0b0;
						background-image: linear-gradient( to right, #b0b0b0 0%, #a0a0a0 20%, #b0b0b0 40%, #b0b0b0 100% );
						background-repeat: no-repeat;
						margin: 4px auto;
					}
					.llms-mini-cert--mock-dot {
						background: #b0b0b0;
						border-radius: 50%;
						display: inline-block;
						content: '';
						height: 24px;
						width: 24px;
					}
					p { margin-bottom: 0; }
```

2022-02-08 10:47 UTC, eri-trabiccolo commented on assets/scss/frontend/_llms-notifications.scss
> +						margin-bottom: 12px;
```suggestion
						margin: 12px auto;
```
Let's set the margin top too. I was using 2020 theme and it had too much space above by default.

2022-02-08 15:50 UTC, thomasplevy commented
@chrisbadgett @willmiddleton-lifterlms @nrherron92 can I get your thoughts on this before merging?

2022-02-08 15:56 UTC, nrherron92 commented
@thomasplevy I like it! Without the sweeping effect I think that takes away the idea that it's loading so that should help on that front (even though I thought that looked cool too!). Regardless, I think it really nice as a mini preview!

2022-02-11 15:52 UTC, thomasplevy commented
Bump @willmiddleton-lifterlms @chrisbadgett

2022-02-15 16:09 UTC, thomasplevy commented
@chrisbadgett @willmiddleton-lifterlms last bump. I'm going to merge this afternoon for release with beta.1

2022-02-15 20:40 UTC, chrisbadgett commented
Looks solid.

2022-02-15 22:27 UTC, merged