Change llmsStudentsSelect2() to use the LifterLMS REST API
gocodebox/lifterlms pull request #2084
Opened 2022-03-28 20:46 UTC by pondermatic

## Description
Changed the `llmsStudentsSelect2()` JavaScript function to use the [LifterLMS REST API "list students" endpoint](https://developer.lifterlms.com/rest-api/#tag/Students/paths/~1students/get) instead of the [`LLMS_AJAX_Handler::query_students()`](https://github.com/gocodebox/lifterlms/blob/6.1.0/includes/class.llms.ajax.handler.php#L398) PHP function.

Fixes LifterLMS Private Areas [60](https://github.com/gocodebox/lifterlms-private-areas/issues/60).

## How has this been tested?
Manually:
1. Add new private post. Select a student. Optionally select a course.
2. LifterLMS -> Reporting -> Sales -> Toggle Filters. Select students.

Checked JavaScript console and PHP error log.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2022-03-28 20:48 UTC, pondermatic commented on assets/js/llms-admin.js
> +					var totalPages = this._request.getResponseHeader( 'X-WP-TotalPages' );
I did not find a "public" way to get the jQuery ajax object, so I used `_request`.

2022-03-28 23:09 UTC, thomasplevy requested changes
Looks good to me, tested it in a few different scenarios and seems to work as expected. I think it might be a bit faster than the old method.

Only change I'd like to see made here is that we also deprecated the AJAX query method that this is replacing: https://github.com/gocodebox/lifterlms/blob/2982a141376d129a8d63f00214e00163196e3842/includes/class.llms.ajax.handler.php#L382-L597 

It is a public method so we shouldn't just remove it, but marking it as deprecated and adding a `_deprecated_function` call would be ideal so that we don't forget to do it later.

2022-03-29 16:08 UTC, thomasplevy requested changes
I'm nitpicking the language but I don't like the idea of having example URLs as the "replacement" in our docs / changelogs. Even having those examples in the REST API docs occassionally result in people not realizing that "example.tld" isn't meant to be replaced with their actual domain.

2022-03-29 16:08 UTC, thomasplevy commented on .changelogs/deprecate-ajax-query-students.yml
> +entry: Deprecated `LLMS_AJAX_Handler::query_students()`. Use LifterLMS REST API 'GET https://example.tld/wp-json/llms/v1/students' instead.
```suggestion
entry: Deprecated `LLMS_AJAX_Handler::query_students()`. Use the [REST API list students](https://developer.lifterlms.com/rest-api/#tag/Students/paths/~1students/get) endpoint instead.
```

2022-03-29 16:08 UTC, thomasplevy commented on includes/class.llms.ajax.handler.php
> +	 * @deprecated [version] `LLMS_AJAX_Handler::query_students()` is deprecated. Use LifterLMS REST API
```suggestion
	 * @deprecated [version] `LLMS_AJAX_Handler::query_students()` is deprecated in favor of the REST API list students endpoint.
```

2022-03-29 16:08 UTC, thomasplevy commented on includes/class.llms.ajax.handler.php
> +		_deprecated_function( __METHOD__, '[version]', 'GET https://example.tld/wp-json/llms/v1/students' );
```suggestion
		_deprecated_function( __METHOD__, '[version]', 'the REST API list students endpoint' );
```

2022-03-29 16:09 UTC, merged