Allow avoiding error returning when updating an llms post meta with the same value as stored in the db
gocodebox/lifterlms pull request #2129
Opened 2022-04-22 10:05 UTC by eri-trabiccolo

## Description

Fixes #909 and needed to fix https://github.com/gocodebox/lifterlms-rest/issues/222
This PR, aside from some code reorganization, just adds this piece of code:
https://github.com/gocodebox/lifterlms/pull/2129/files#diff-3f0337a1db5180a72d1b5434e90b08b7b0f4b7ee5997ac4dd50efa7b6d3c21a8R1482-R1497

## How has this been tested?
existing unit tests (doesn't introduce any drawback since the old behavior is the default one).
working on new unit tests.

## Screenshots 

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2022-04-22 10:59 UTC, eri-trabiccolo commented
@gocodebox/engineering 
while I work on unit tests, if you got time, may I have your opinion on the strategy?
Thanks

2022-04-28 14:08 UTC, thomasplevy requested changes
This looks pretty good to me. This is such a messy area of the codebase that this honestly seems to make it *more* messy to me but refactoring the code into separate methods is a good step towards making all of this a bit more testable and less fragile to maintain longterm.

I haven't physically run any tests but it looks solid given that existing unit tests are passing and the new tests you've added work. However, I'd like to see a bit more test coverage added here, specifically:

1) Usage of the new param in `set()` method isn't covered at all.
2) `empty_data` error condition in `set_bulk()` isn't covered 
3) `invalid_data` error condition in `set_bulk()` isn't covered
4) method `is_meta_value_same_as_stored_value()` is only tested for scalar values (strings). Tests could be written to test this method directly, ideally with every scalar type and at least one non scalar type being passed in. Using `LLMS_Unit_Test_Util::call_private_method()` so you can just pass stuff in directly.
5) You technically did not add anything related to setting post properties but there's no coverage on post properties here (I know other model tests pick it up but it wouldn't be too hard to add some post properties here while you're at it.

2022-04-28 14:08 UTC, thomasplevy commented on includes/abstracts/abstract.llms.post.model.php
> +	 * @return array|false False if nothing to set. An array that contains all the post properties and all the metas to set, otherwise.
```suggestion
	 * @param array $model_array Associative array of key/val pairs.
	 * @return array|bool Returns `false` if nothing to set or an array that contains all the post properties and all the metas to set.
```

2022-04-28 16:14 UTC, eri-trabiccolo commented
> This looks pretty good to me. This is such a messy area of the codebase that this honestly seems to make it _more_ messy to me but refactoring the code into separate methods is a good step towards making all of this a bit more testable and less fragile to maintain longterm.

Yeah

> I haven't physically run any tests but it looks solid given that existing unit tests are passing and the new tests you've added work. However, I'd like to see a bit more test coverage added here, specifically:
> 
> 1. Usage of the new param in `set()` method isn't covered at all.

True.

> 2. `empty_data` error condition in `set_bulk()` isn't covered
> 3. `invalid_data` error condition in `set_bulk()` isn't covered

Yeah, I haven't added unit tests for _old_ code.

> 4. method `is_meta_value_same_as_stored_value()` is only tested for scalar values (strings). Tests could be written to test this method directly, ideally with every scalar type and at least one non scalar type being passed in. Using `LLMS_Unit_Test_Util::call_private_method()` so you can just pass stuff in directly.

You're right.

> 5. You technically did not add anything related to setting post properties but there's no coverage on post properties here (I know other model tests pick it up but it wouldn't be too hard to add some post properties here while you're at it.

Because this PR didn't change the behavior on post properties: _old_ code.

I can add more tests coverage though <3

2022-04-28 22:30 UTC, thomasplevy commented
@eri-trabiccolo I realize that you didn't add tests for old code but since you're moving that old code and writing code all around it it's a good opportunity to add some tests to that old code.

2022-04-29 07:17 UTC, eri-trabiccolo commented
Yeah sorry, what I meant was that despite what it looks like the PR introduces very little changes, and those are tested.
But yeah improving the code coverage is always good you're right.

2022-05-02 10:42 UTC, eri-trabiccolo commented
@thomasplevy added various tests.

2022-05-02 16:26 UTC, thomasplevy approved these changes

2022-05-02 16:26 UTC, merged