Add llms_is_option_secure().
gocodebox/lifterlms pull request #2195
Opened 2022-07-02 00:23 UTC by pondermatic

## Description
Adds a `llms_is_option_secure()` function that tests if the given option is defined in an environment variable of a constant.

Fixes part of gocodebox/lifterlms-gateway-paypal#73.

## How has this been tested?
New unit test.

## Types of changes
New development feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2022-07-04 14:52 UTC, eri-trabiccolo requested changes
Looks good.

2022-07-04 14:52 UTC, eri-trabiccolo commented on includes/functions/llms-functions-options.php
> +	if ( empty( $option_name ) ) {
```suggestion
	if ( '' === $option_name ) ) {
```
right?

2022-07-04 20:08 UTC, pondermatic commented on includes/functions/llms-functions-options.php
> +	if ( empty( $option_name ) ) {
Your suggestion is a more specific comparison and is probably better in this case.

2022-07-05 07:16 UTC, eri-trabiccolo approved these changes

2022-07-05 17:41 UTC, merged