Introduce something like a database ORM
gocodebox/lifterlms pull request #2297
Opened 2022-11-09 20:34 UTC by thomasplevy

## Description

This PR introduces a new set of classes aimed to reduce repetition in database table creation and management. It also includes schema files for each existing database table in the LifterLMS core plugin.

This PR introduces functionality for registering and managing tables.

The next steps would be to utilize the `LLMS_Database_Table` class within object models to setup getters and setters based on the already-defined schema... Also query classes could utilize this data to automatically generate query classes based off the data available in the table's schema.

This is likely not completely ready for production yet. I wanted to open the PR to review and improve.

This PR also includes a simple PHP CLI script for automatically generating markdown docs describing database tables. I'd like to package that script up a bit differently so that add-ons could also easily utilize it to generate documentation. I'm considering bundling it into an WP (LLMS) CLI command so that an add-on (which already depends on LifterLMS) can easily generate it's own documentation.

My plan for this markdown file would be to (eventually) pull it into developer.lifterlms.com via the incomplete "handbook" importer: https://github.com/gocodebox/developer.lifterlms.com/pull/29

Other add-ons that have their own markdown database docs could be added the the handbook(s) as well later on.

This was inspired, pretty heavily, by BerlinDB. I initially wished to use BerlinDB directly but I had a few problems with it and ultimately decided that we could manage this internally in a way that's better for us without having to worry about another plugin's requirements causing issues for us.

## How has this been tested?
+ Manually
+ New and existing tests

## Screenshots 

## Types of changes
+ New feature / enhancement 

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2022-11-16 16:10 UTC, eri-trabiccolo commented on includes/class-llms-database-table.php
> +	protected $wpdb;
I don't know whether this makes all this sense here, does it?
We're referencing to a global in a protected property for which we would have to ensure bw compatibility?!
Let's use the global where needed.

2022-11-16 16:23 UTC, thomasplevy commented on includes/class-llms-database-table.php
> +	protected $wpdb;
This makes testing "easier"

When we want to mock a particular portion of the global we can simply overwrite the class property in favor of mocking the whole global.

EG:

```
$mock_wpdb = new class {
  function has_cap( $cap ) {
     return false;
  }
}
$table = new LLMS_Database_Table( ... );
LLMS_Unit_Test_Util::set_private_property_value( $table, 'wpdb', $mock_wpdb );
```

This feels like a better approach than actually physically mocking the global. We could of course mock the global too and maybe that's better but I don't like that as much.

As far as backwards compatibility is concerned, if we drop it we drop it. But... I don't forsee `wpdb` ever being dropped from WordPress so we'll probably never need to drop it either. And if we decide we don't need it anymore it's not hard to deprecate.

Maybe my thinking is shortsighted though?

2022-11-16 16:25 UTC, eri-trabiccolo commented on includes/class-llms-database-table.php
> +	protected $wpdb;
I don't know, I feel it's not a good practice overdoing something for "more easy testing" purposes only. But ok it's fine.

2022-11-17 17:09 UTC, eri-trabiccolo commented on includes/class-llms-database-table.php
> +
shall we cache the computed schema?

2022-11-18 08:37 UTC, eri-trabiccolo requested changes
Looks a good starting point

2022-11-18 08:37 UTC, eri-trabiccolo commented on includes/schemas/database/quiz-attempts.php
> + * Table Schema Definition: lifterlms_user_postmeta
```suggestion
 * Table Schema Definition: lifterlms_quiz_attempts
```

2022-11-18 08:37 UTC, eri-trabiccolo commented on includes/schemas/database/sessions.php
> +			'type'        => 'id',
this is a UNIX timestamp actually...

2022-11-18 08:37 UTC, eri-trabiccolo commented on includes/schemas/database/sessions.php
> +			'description' => 'The session data, stored as a JSON object.',
isn't actually a serialized array?

2022-11-23 13:15 UTC, eri-trabiccolo commented
we're using php8 code here, let's not forget to raise the min required PHP version.

2024-05-10 14:38 UTC, closed without merging