Fixes #2322
gocodebox/lifterlms pull request #2399
Opened 2023-03-23 12:53 UTC by actuallyakash

## Description
Added query to remove order notes on Plugin Uninstallation.

Fixes #2322

## How has this been tested?
Manually, on local machine.

## Types of changes
Bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2023-03-27 10:10 UTC, eri-trabiccolo requested changes
see https://github.com/gocodebox/lifterlms/issues/2322#issuecomment-1484868450
Also, can you update the file header version's placeholder?
from 
`@version 6.0.0 `
to
`@version [version]`

2023-04-03 06:53 UTC, actuallyakash commented
This is done!

2023-04-07 08:30 UTC, eri-trabiccolo requested changes

2023-04-07 08:30 UTC, eri-trabiccolo commented on .changelogs/fix_2322.yml
> +entry: Added query to remove order comments.
```suggestion
entry: Added query to remove order comments on plugin uninstall when the constant `LLMS_REMOVE_ALL_DATA` is set to `true`.
```

2023-04-07 08:33 UTC, actuallyakash commented on .changelogs/fix_2322.yml
> +entry: Added query to remove order comments.
thanks :D

Done.

2023-04-07 08:39 UTC, eri-trabiccolo approved these changes

2023-06-02 07:01 UTC, merged