Add dashboard widget
gocodebox/lifterlms pull request #2405
Opened 2023-03-29 11:07 UTC by seothemes

## Description

Adds a new widget to the WordPress dashboard screen `/wp-admin/index.php`.

## How has this been tested?

Manually

## Screenshots

<img width="552" alt="first pass dashboard widget design" src="https://user-images.githubusercontent.com/24793388/228514384-bd8a7e69-ae0c-4096-8e9e-5c0577d9062f.png">

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2023-03-31 09:01 UTC, eri-trabiccolo requested changes
doc changes.
Also this doesn't seem to correctly work: the widgets in the dashboard page do not show up, loading spinner forever.

Looks like a js error: datepicker missing, we need to enqueue jquery-datepicker on that page, or change the analytics js so to not break when the datepicker is not there. We actually don't need a datepicker tho only show those widgets...
`Uncaught TypeError: $(...).datepicker is not a function [llms-analytics.js:66:28]`

2023-03-31 09:01 UTC, eri-trabiccolo commented on assets/js/llms-analytics.js
> + * @version [version]
```suggestion
 * @version [version]
 *
```

2023-03-31 09:01 UTC, eri-trabiccolo commented on assets/js/llms-analytics.js
> +		 * @version [version]
```suggestion
```
Also if you wanna take the occasion to improve the docblock of this method... :D <3

2023-03-31 09:01 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.dashboard-widget.php
> +	 * Constructor
```suggestion
	 * Constructor.
```

2023-03-31 09:01 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.dashboard-widget.php
> +	 * Add the dashboard widget
```suggestion
	 * Add the dashboard widget.
```

2023-03-31 09:01 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.dashboard-widget.php
> +	 * Output the dashboard widget
```suggestion
	 * Output the dashboard widget.
```

2023-03-31 09:01 UTC, eri-trabiccolo commented on templates/admin/reporting/tabs/widgets.php
should update the version of this file

2023-03-31 09:01 UTC, eri-trabiccolo commented on includes/admin/class.llms.admin.assets.php
> +		if ( in_array( $screen->base, array( 'lifterlms_page_llms-reporting', 'lifterlms_page_llms-dashboard', 'dashboard' ), true ) ) {
missing docblock's changelog update

2023-04-03 10:44 UTC, eri-trabiccolo requested changes
docs <3

2023-04-03 10:44 UTC, eri-trabiccolo commented on assets/js/llms-analytics.js
> +			if ( $( '.llms-datepicker' ).length && $.fn.datepicker ) {
I would add a changelog to the `bind()` docblock to log the change.

2023-04-03 10:44 UTC, eri-trabiccolo commented on assets/js/llms-analytics.js
> +		 * @param obj $widget jQuery selector of the widget element
```suggestion
		 * @param obj $widget The jQuery selector of the widget element.
```

2023-04-03 10:44 UTC, eri-trabiccolo commented on assets/js/llms-analytics.js
> +		 * @version [version]
I'd remoe the version here, we use the `version` tag on file headers only.

2023-04-04 07:07 UTC, eri-trabiccolo approved these changes

2023-04-10 13:45 UTC, kimcoleman approved these changes

2023-04-21 12:52 UTC, eri-trabiccolo commented
Skipping this for 7.1.3, because it's a minor change, will be merged in 7.2

2023-06-02 09:16 UTC, merged