Add inherit option to Course Outline block and increase max number of…
gocodebox/lifterlms pull request #2508
Opened 2023-08-08 13:54 UTC by seothemes

## Description

- Adds `Inherit from current course` option to Course Outline block when editing Single Course template.
- Increase maximum number of courses shown in drop down select (for all blocks using component)

## How has this been tested?

Manually

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] This PR requires and contains at least one changelog file. 
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2023-08-08 14:20 UTC, eri-trabiccolo requested changes
Looks good but I'm not gonna merge this in the upcoming release.
We have the same issue with the Course Information block (not inheriting).
Would be great if for all the blocks that require a course to be specified - or they inherit it from the context (e.g. what if you're in a lesson template?) - we display kind of a placeholder, that mimics the block aspect.
About:
`		// Show the first course when in Editor if none selected.`

What if the first course has no sections?

2023-08-14 13:39 UTC, eri-trabiccolo requested changes
Hey Lee, you must have missed my last review's comment:

```
Looks good but I'm not gonna merge this in the upcoming release.
We have the same issue with the Course Information block (not inheriting).
Would be great if for all the blocks that require a course to be specified - or they inherit it from the context (e.g. what if you're in a lesson template?) - we display kind of a placeholder, that mimics the block aspect.
About:
		// Show the first course when in Editor if none selected.

What if the first course has no sections?

```

2023-08-14 13:39 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.shortcode.course.element.php
> +	 * @version [version] Add fallback for editor block rendering.
```suggestion
	 * @since [version] Add fallback for editor block rendering.
```

2023-08-14 13:39 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.shortcode.course.element.php
> +		if ( in_array( $course->post_type, array( 'lesson', 'llms_quiz' ) ) ) {
```suggestion
		if ( in_array( $course->post_type, array( 'lesson', 'llms_quiz' ), true ) ) {
```
what about assignments though? see the filter `llms_course_children_post_type` assignments add-on leverage as well.

2023-08-14 13:39 UTC, eri-trabiccolo commented on includes/abstracts/abstract.llms.shortcode.course.element.php
> +
instead of mixing concepts, can't we have filters so that FROM the blocks shortcode we alter the placeholder course id from there?...

2023-08-14 13:39 UTC, eri-trabiccolo commented on includes/shortcodes/class.llms.shortcode.course.outline.php
> +	 * @since [version] Add fallback for editor block rendering.
```suggestion
	 * @since 3.19.2 Unknown.
	 * @since [version] Add fallback for editor block rendering.
```

2025-07-18 12:42 UTC, closed without merging

2025-07-18 12:42 UTC, brianhogg commented
Closing, can open a separate issue to re-do if it popups up in priority.