Preventing browser caching of redirects.
gocodebox/lifterlms pull request #2516
Opened 2023-08-30 14:48 UTC by actuallyakash

Added support for preventing browser caching of redirects.

## How has this been tested?
Manually.

## Types of changes

Bug fix

## Checklist:
- [x] This PR requires and contains at least one changelog file. 
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards. 

Ref: [HS - 225138](https://secure.helpscout.net/conversation/2344116479/225138?folderId=349322)

2023-08-31 08:40 UTC, eri-trabiccolo requested changes

2023-08-31 08:40 UTC, eri-trabiccolo commented on includes/functions/llms-functions-wrappers.php
> +		nocache_headers(); // Prevent caching of redirects.
I'd limi this to 302 redirects for now as said on slack:
https://teamcodebox.slack.com/archives/C055HEK214N/p1693314434326109?thread_ts=1693311193.922769&cid=C055HEK214N

2023-08-31 13:06 UTC, actuallyakash commented on includes/functions/llms-functions-wrappers.php
> +		nocache_headers(); // Prevent caching of redirects.
fixed.

2023-09-01 08:20 UTC, eri-trabiccolo commented
@actuallyakash have you tested this, works fine? No unwanted side effects?

2023-09-01 09:59 UTC, actuallyakash commented
> @actuallyakash have you tested this, works fine? No unwanted side effects?

yes @eri-trabiccolo 
Didn't face any side effects. I tested the functionality by purchasing the course with and without `disable cache` and it's working fine.

2023-09-01 10:54 UTC, eri-trabiccolo requested changes

2023-09-01 10:54 UTC, eri-trabiccolo commented on includes/functions/llms-functions-wrappers.php
> +	 * @since [version] Added `nocache_headers()` to prevent caching of redirects.
```suggestion
	 * @since [version] Added `nocache_headers()` to prevent caching of temporary redirects.
```

2023-09-01 10:54 UTC, eri-trabiccolo commented on .changelogs/dev.yml
> +entry: Added `nocache_headers()` to prevent browser caching for redirects.
```suggestion
entry: Added `nocache_headers()` to prevent browser caching for temporary redirects.
```

2023-09-01 14:44 UTC, eri-trabiccolo approved these changes

2023-09-04 09:10 UTC, merged