Add voucher table cleanup when an llms_voucher post is deleted
gocodebox/lifterlms pull request #2567
Opened 2023-11-07 00:06 UTC by bsetiawan88

## Description
The voucher relationships in `lifterlms_vouchers_codes` are cleaned up when vouchers are deleted.

Fixes #1087

## How has this been tested?
Manually.

## Types of changes
Bug fix

## Checklist:
- [x] This PR requires and contains at least one changelog file. 
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2023-11-07 05:40 UTC, actuallyakash commented
Hey @bsetiawan88 

Thanks for the contribution.

I'm gonna add:

- some docblocks
- a changelog file

2023-11-07 05:47 UTC, actuallyakash approved these changes

2023-11-07 07:18 UTC, actuallyakash requested changes
Failing tests needs to be fixed.

2024-05-08 13:54 UTC, brianhogg commented
@bsetiawan88  I don't seem to be able to push changes up to this fork, so I'll close this one and I've created a new one with props to you. Thanks again! https://github.com/gocodebox/lifterlms/pull/2652

2024-05-08 13:54 UTC, closed without merging